openapi: '3.0.0'
info:
  version: '1.00'
  title: 'test-apis'
  description: APIs for testing and finding mistakes
servers:
  - url: http://localhost/api
paths:
  /auth/login:
    post:
      tags:
        - Auth
      summary: Login
      responses:
        200:
          description: Successfully logged in
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/Login'
        400:
          description: Probably bad credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestError'
        500:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerError'
  /auth/register:
    post:
      tags:
        - Auth
      summary: Register
      responses:
        201:
          description: Successfully registered
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Register'
        422:
          description: Unprocessable content
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnprocessableContentError'
        500:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerError'
  /auth/logout:
    post:
      tags:
        - Auth
      summary: Logout
      responses:
        204:
          description: Successfully logged out. No content.
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerError'
        500:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerError'
  /news:
    get:
      tags:
        - News
      summary: Browse news
      responses:
        200:
          description: News
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/News'
        500:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerError'
    post:
      tags:
        - News
      summary: Create news
      security:
        - bearerAuth: [ ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                content:
                  type: string
      responses:
        201:
          description: news created
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/News'
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerError'
        422:
          description: Unprocessable content
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnprocessableContentError'
        500:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerError'
  /news/{id}:
    get:
      tags:
        - News
      summary: Show news
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        200:
          description: News
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/News'
        500:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerError'
    patch:
      tags:
        - News
      summary: Partially update news
      security:
        - bearerAuth: [ ]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  required: false
                content:
                  type: string
                  required: false
      responses:
        204:
          description: Updated
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerError'
        422:
          description: Unprocessable content
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnprocessableContentError'
        500:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerError'
    put:
      tags:
        - News
      summary: update (replace) news
      security:
        - bearerAuth: [ ]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  required: true
                content:
                  type: string
                  required: true
      responses:
        204:
          description: Updated
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerError'
        422:
          description: Unprocessable content
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnprocessableContentError'
        500:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerError'
    delete:
      tags:
        - News
      summary: delete news
      security:
        - bearerAuth: [ ]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        204:
          description: Deleted
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerError'
        500:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerError'

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        email:
          type: string
        email_verified_at:
          type: string
          example: "2022-12-24 13:30:33"
    Login:
      type: object
      properties:
        access_token:
          type: string
        type:
          type: string
        expires_in:
          type: integer
        user:
          $ref: "#/components/schemas/User"
    Register:
      type: object
      properties:
        message:
          type: string
          example: Successfully registered
        data:
          type: object
          properties:
            user:
              type: object
              properties:
                id:
                  type: integer
                email:
                  type: string
                name:
                  type: string
    News:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        content:
          type: string
    BadRequestError:
      type: object
      required:
        - message
        - status
      properties:
        message:
          description: A human readable error message
          type: string
        status:
          description: Status 0 or 1
          type: integer
    ServerError:
      type: object
      required:
        - message
      properties:
        message:
          description: A human readable error message
          type: string
    UnprocessableContentError:
      type: object
      properties:
        message:
          type: string
        errors:
          type: object
          properties:
            example_field:
              type: array
              items:
                type: string
                example: "The example_field is required"
    UnauthorizedError:
      type: object
      properties:
        message:
          type: string
          example: Unauthenticated
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: [ ]
